#!/bin/bash

#
# Not for use in production.
#
# Build project venv, run migrations, Run Django development server
# Poll upstream master branch
# If changes are present, pull them in and restart this script (allowing this script to be updated)
#

POLL_DELAY=10
BRANCH=master
SERVER_DIR=../web_core # relative to SCRIPT_DIR
SCRIPT_DIR=../deploy # relative to SERVER_DIR
PREFIX="> > > > >  "


echo $PREFIX "Killing Django server"
fuser -k 8000/tcp

echo $PREFIX "Clearing virtualenv"
cd $SERVER_DIR && make clear_venv

echo $PREFIX "Building virtualenv"
cd $SERVER_DIR && make venv

echo $PREFIX "Running migrations"
cd $SERVER_DIR && make migrate

echo $PREFIX "Starting Django server"
cd $SERVER_DIR && make prodserver &

while :
do
    # Fetch changes
    git remote update

    # Compare commit hash of remote and head
    if [ $(git rev-parse HEAD) != $(git rev-parse @{u}) ]; then
        echo $PREFIX "Detected Changes" $(date)

        echo $PREFIX "Pulling the latest from" $BRANCH
        git pull -u origin $BRANCH

        echo $PREFIX "Restarting this script"
        cd $SCRIPT_DIR && ./$(basename $0) && exit
    else
        echo $PREFIX "No changes."
    fi
    sleep $POLL_DELAY
done
